### ISSUE TITLE
iOS 8 Extensions?

### ISSUE THREAD

**Issue by vicc** [LukasCZ/GSTouchesShowingWindow#1]
This is awesome! However how do you propose getting this to work in a keyboard extension? I am using a storyboard in my extension, but can't seem to get it working.

**Comment by LukasCZ** [comment]
Hi Alex, thanks! At the moment, I can't see how to do that. This UIWindow subclass relies on the -sendEvent method, which is only in UIWindow. And because keyboard extensions are placed in their own window, you can't just override the -sendEvent method there. Perhaps it could be possible with method swizzling, but I am not very experienced with it. Sorry :/.

**Comment by LukasCZ** [comment]
Hi Alex, mere 3 years later, I've built in support for App extensions (tested with Keyboard and Today extensions, but it should work with others as well). I basically separated out the logic of handling touches and showing the image indicators into `GSTouchesShowingController`, and then created a gesture recognizer (`GSTouchesShowingGestureRecognizer`) which you can add to your view in `-viewDidLoad`. You can take a look at the updated Readme to find out more. I know this is probably too late to be relevant for you anymore, but I figured I'll update you anyway.
