### ISSUE TITLE
Error with ios9

### ISSUE THREAD

**Issue by mhartington** [LukasCZ/GSTouchesShowingWindow#7]
Getting this error with ios9

```
2015-09-10 16:03:42.149 tmp[4140:2033972] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.4/UIApplication.m:3267
2015-09-10 16:03:42.155 tmp[4140:2033972] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(0x18407da94 0x198ac7f80 0x18407d964 0x184f6c09c 0x189830620 0x18982d2e8 0x18dcd37ec 0x18dcd3b6c 0x1840350dc 0x184034b70 0x184032870 0x183f618a0 0x1895fb1ec 0x1895f60d4 0x1000a38d0 0x1993168b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by julestburt** [comment]
Having the same experience with latest version of Xcode that installed itself! Xcode 7.0

**Comment by appscarvajal** [comment]
i'm Getting this error with the new actucalization of iOS 9 

**\* Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.17/UIApplication.m:3294
2015-10-08 16:59:17.652 PaginasAmarillas[3379:1880090] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
**\* First throw call stack:
(0x1837f4f5c 0x1982fbf80 0x1837f4e2c 0x1846e3f3c 0x188fec688 0x188fe92e4 0x18d53b7ec 0x18d53bb6c 0x1837ac5a4 0x1837ac038 0x1837a9d38 0x1836d8dc0 0x188db80ac 0x188db2f44 0x1000b10d8 0x198b268b8)
libc++abi.dylib: terminating with uncaught exception of tape NSException

Anyone have idea about it ?

**Comment by pushkin2023** [comment]
Anyone did fix this issues? I have the same issue with Xcode 7 and iOS 9 (on iOS 8 it runs ok).

**Comment by LukasCZ** [comment]
Hey guys, sorry for the inactivity on my part, I've been busy with work. I will look into it tomorrow, and I am determined to fix it.

**Comment by LukasCZ** [comment]
So, I figured out the problem. Those of you who experienced the crash are probably still using .xib file for your application window. As explained in the README, you need to change the main window's class (as opposed to overriding the -window method - that works only when using Storyboards).
I will update the README to make this more clear.

**Comment by LukasCZ** [comment]
Regarding my previous comment - I found out using a very old Xcode project that I have on my computer. If you are looking to fix the crashing under iOS 9, except for removing the -window method, you should also replace the following line in your App Delegate:
**[window addSubview:[navigationController view]];**
with this one:
**window.rootViewController = navigationController;**
(if you are not using navigation controller, just change it to whatever view controller you are using. You get the idea.)
